export const PUBLIC_CARD_FIELDS = [
  "id",
  "name",
  "title",
  "description",
  "registryNamespace",
  "websiteUrl",
  "repository",
  "icons",
  "installs",
  "status",
  "visibility",
  "latestVersion",
  "qualityScore",
  "categories",
  "createdAt",
  "updatedAt",
].join(",");
