name: Security Checks
on:
  pull_request: null
  push:
    branches:
      - master
permissions:
  contents: read
  pull-requests: read
jobs:
  security:
    uses: abhi1693/actions/.github/workflows/security.yml@34e92ba1eee6a47e9b10f13e2180114fc01b6027
    with:
      runs-on: ubuntu-latest
      node-version: '24'
      workflow-lint: false
      gitleaks-config: .gitleaks.toml
      npm-audit: true
      npm-severity: high
      npm-include-dev: false
      python-audit: true
      python-directory: hub/backend
      python-version: '3.13'
      python-extras: '["dev"]'
      python-include-dev: true
